---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build:
    desc: Build image
    vars:
      TAG: comp370:latest
    cmd: |
      mkdir -p .cache
      {{.RUNTIME}} build -f docker/Dockerfile -t {{.TAG}} .

  run:
    desc: Run container
    vars:
      TAG: comp370:latest
    cmd: |
      {{.RUNTIME}} run --rm -it {{.TAG}}
