---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  check:
    desc: Check TOML files
    silent: true
    cmds:
      - tombi lint .
      - tombi fmt --check .

  fix:
    desc: Fix TOML files
    silent: true
    cmds:
      - tombi fmt . &> /dev/null
